// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package com.srini.protobuf.model;

/**
 * The type Stock protos.
 */
public final class StockProtos {
  private StockProtos() {}

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

    /**
     * The Internal static stock descriptor.
     */
    static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stock_descriptor;
    /**
     * The Internal static stock field accessor table.
     */
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stock_fieldAccessorTable;

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013stock.proto\"3\n\005Stock\022\014\n\004name\030\001 \001(\t\022\014\n\004" +
      "isin\030\002 \001(\005\022\016\n\006volume\030\003 \001(\005B#\n\022com.srini." +
      "protobufB\013StockProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stock_descriptor,
        new String[] { "Name", "Isin", "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
